solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot", "LeftHand", "RightHand"]#, "Com"]
    - ["Com"]
    #- ["RHandOrientation", "LHandOrientation"]
    - ["Postural"]
    
constraints: ["JointLimits"] #, "VelocityLimits"]

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"
    lambda: 1.0
    #indices: [0, 1, 2]
    
RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"
    lambda: 1.0
    #indices: [0, 1, 2]
    
Postural:
    type: "Postural"
    lambda: 0.1
    
LeftHand:
    type: "Cartesian"
    distal_link: "TCP_L"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
RightHand:
    type: "Cartesian"
    distal_link: "TCP_R"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]

TorsoRPY:
    type: "Cartesian"
    distal_link: "torso"
    lambda: 1.0
    indices: [3, 4, 5]

Com:
    type: "Com"
    lambda: 0.1

Head:
    type: "Cartesian"
    distal_link: "Head"
    lambda: 1.0
    
RHandOrientation:
    type: "Subtask"
    task: "RightHand"
    indices: [4]
    lambda: 0.1
    weight: 10
    
LHandOrientation:
    type: "Subtask"
    task: "LeftHand"
    indices: [4]
    lambda: 0.1
    weight: 10
    
Waist:
    type: "Cartesian"
    distal_link: "Waist"
    indices: [0, 2]
