solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot"]
    #- ["Waist"]

constraints: ["JointLimits"]

JointLimits:
    type: "JointLimits"

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"

Waist:
    type: "Cartesian"
    distal_link: "Waist"
    lambda: 0.1
    indices: [3, 4, 5]

Com:
    type: "Com"
    lambda: 1.0
    indices: [0, 1, 2]

Postural:
    type: "Postural"
    lambda: 0.0

LeftHand:
    type: "Cartesian"
    distal_link: "TCP_L"
    lambda: 1.0

RightHand:
    type: "Cartesian"
    distal_link: "TCP_R"
    lambda: 1.0
    # indices: [0, 1, 2]

