solver_options:
    regularization: 1e-4
    back_end: "qpoases"

stack:
    - ["l_sole_wrench", "r_sole_wrench", "r_ball_tip_wrench", "l_ball_tip_wrench"] #, "UnderactuatedDyn"]
    # - ["Com"]

constraints:
    - "UnderactuatedDyn"
    - "l_sole_fc"
    - "r_sole_fc"
    - "l_ball_tip_fc"
    - "r_ball_tip_fc"
    #- "l_ball_tip_d_fc"
    #- "r_ball_tip_d_fc"
    - "l_sole_F_lims"
    - "r_sole_F_lims"
    - "l_ball_tip_F_lims"
    - "r_ball_tip_F_lims"
    #- "l_ball_tip_d_F_lims"
    #- "r_ball_tip_d_F_lims"
    - "LeftCoP"
    - "RightCoP"
    - "NormalTorqueRight"
    - "NormalTorqueLeft"

definitions:
 - &left_ee l_ball_tip
 - &right_ee r_ball_tip

Com:
    type: "Com"
    lambda: 1.0
    weight: 1

NormalTorqueRight:
    lib_name: libcartesio_acceleration_support.so
    type: "NormalTorque"
    link: "r_sole"
    friction_coeff: 0.4
    x_limits: [-0.05, 0.05]
    y_limits: [-0.025, 0.025]

NormalTorqueLeft:
    lib_name: libcartesio_acceleration_support.so
    type: "NormalTorque"
    link: "l_sole"
    friction_coeff: 0.4
    x_limits: [-0.05, 0.05]
    y_limits: [-0.025, 0.025]

LeftCoP:
    lib_name: libcartesio_acceleration_support.so
    type: "CoP"
    link: "l_sole"
    x_limits: [-0.04, 0.04]
    y_limits: [-0.04, 0.04]

RightCoP:
    lib_name: libcartesio_acceleration_support.so
    type: "CoP"
    link: "r_sole"
    x_limits: [-0.04, 0.04]
    y_limits: [-0.04, 0.04]


r_sole_wrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: "r_sole"
    #weight: [1, 1, 1, 1e3, 1e3, 1e3]
    #weight: 1e-2

l_sole_wrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: "l_sole"
    #weight: [1, 1, 1, 1e3, 1e3, 1e3]
    #weight: 1e-2

r_ball_tip_wrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: *right_ee
    #weight: [1, 1, 1, 1e3, 1e3, 1e3]
    #weight: 1e-2

l_ball_tip_wrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: *left_ee
    #weight: [1, 1, 1, 1e3, 1e3, 1e3]
    #weight: 1e-2

r_ball_tip_d_wrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: "r_ball_tip_d"
    #weight: [1, 1, 1, 1e3, 1e3, 1e3]
    #weight: 1e-2

l_ball_tip_d_wrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: "l_ball_tip_d"
    #weight: [1, 1, 1, 1e3, 1e3, 1e3]
    #weight: 1e-2

r_sole_fc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: "r_sole"
    friction_coeff: 0.91
#    local: true

l_sole_fc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: "l_sole"
    friction_coeff: 0.91
#    local: true

r_ball_tip_fc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: *right_ee
    friction_coeff: 0.91
#    local: true

l_ball_tip_fc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: *left_ee
    friction_coeff: 0.91
#    local: true

r_ball_tip_d_fc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: "r_ball_tip_d"
    friction_coeff: 1.15
#    local: true

l_ball_tip_d_fc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: "l_ball_tip_d"
    friction_coeff: 1.15
#    local: true

r_sole_F_lims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: "r_sole"
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000,  0, 0, 0]

l_sole_F_lims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: "l_sole"
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000, 0, 0, 0]

r_ball_tip_F_lims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: *right_ee
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000,  0, 0, 0]

l_ball_tip_F_lims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: *left_ee
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000, 0, 0, 0]

r_ball_tip_d_F_lims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: "r_ball_tip_d"
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000,  0, 0, 0]

l_ball_tip_d_F_lims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: "l_ball_tip_d"
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000, 0, 0, 0]

LHandWrench:
    lib_name: libcartesio_acceleration_support.so
    type: "Force"
    link: "l_wrist"
    weight: [1, 1, 1, 1e3, 1e3, 1e3]

LHandFc:
    lib_name: libcartesio_acceleration_support.so
    type: "FrictionCone"
    link: "l_wrist"

LHandFlims:
    lib_name: libcartesio_acceleration_support.so
    type: "ForceLimits"
    link: "l_wrist"
    min: [-1000, -1000, -1000, 0, 0, 0]
    max: [1000, 1000, 1000, 0, 0, 0]


UnderactuatedDyn:
    lib_name: libcartesio_acceleration_support.so
    type: "DynamicFeasibility"
    contacts: ["l_sole", "r_sole", *left_ee, *right_ee]
    weight: [1e1, 1e1, 1e1, 1e1, 1e1, 1e1]
    dynamics: false

postural:
    lib_name: libcartesio_acceleration_support.so
    type: "Postural"
    lambda: 0.01






