solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot", "LeftHand", "RightHand"]
#   - ["LeftFoot", "RightFoot", "LeftHand", "RightHand", "Com"]
#    - ["Postural"]
    
constraints: ["JointLimits"] #, "VelocityLimits"]

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"
    lambda: 1.0
    #indices: [0, 1, 2]
    
RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"
    lambda: 1.0
    #indices: [0, 1, 2]
    
Postural:
    type: "Postural"
    lambda: 0.3
    
LeftHand:
    type: "Cartesian"
    distal_link: "TCP_L"
    lambda: 1.0
    indices: [0, 1, 2]
    
RightHand:
    type: "Cartesian"
    distal_link: "TCP_R"
    lambda: 1.0
    indices: [0, 1, 2]

TorsoRPY:
    type: "Cartesian"
    distal_link: "torso"
    lambda: 1.0
    indices: [3,4,5]

Com:
    type: "Com"
    lambda: 0.5
    indices: [0, 1, 2]

Head:
    type: "Cartesian"
    distal_link: "Head"
    lambda: 1.0