solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot", "LeftHandC", "RightHandC", "LeftHandD", "RightHandD"]
    - ["Com"]
    - ["Postural"]
    
constraints: ["JointLimits"] #, "VelocityLimits"]

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
LeftHandC:
    type: "Cartesian"
    distal_link: "TCP_L"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
RightHandC:
    type: "Cartesian"
    distal_link: "TCP_R"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
LeftHandD:
    type: "Cartesian"
    distal_link: "l_ball_tip_d"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
RightHandD:
    type: "Cartesian"
    distal_link: "r_ball_tip_d"
    lambda: 1.0
    #indices: [0, 1, 2, 3, 4]
    
Com:
    type: "Com"
    lambda: 0.1
    weight: 0.1
        
Postural:
    type: "Postural"
    lambda: 0.1
