state_validity_check:
    - self_collision

self_collision:
    type: "CollisionCheck"
    include_environment: true

RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000

state_space:
    type: "Atlas"
