#manifold:
#    param_name: "problem_description_constraint"

state_validity_check:
    - collisions

collisions:
    type: "CollisionCheck"
    include_environment: true


RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000

state_space:
    type: "Atlas"

#control_space:
#    duration: 0.01
